sonar.projectKey=Hikotopp_FoodTrack
sonar.organization=hikotopp
sonar.projectName=FoodTrack
sonar.sourceEncoding=UTF-8

sonar.sources=springboot-application/src/main/java,foodtrack/src
sonar.tests=springboot-application/src/test/java,foodtrack/src
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts,**/assets/**,**/favicon.ico
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/security/**,**/validation/**,**/*Request.java,**/*Response.java,**/*Mapper.java,**/entity/**,**/environment*.ts,**/main.ts,**/*.routes.ts,**/*.config.ts

sonar.java.binaries=springboot-application/target/classes
sonar.java.test.binaries=springboot-application/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=springboot-application/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=foodtrack/coverage/foodtrack/lcov.info
