# ===============================
# CONFIG BASE (GENÉRICA)
# ===============================

spring.profiles.active=local

# JPA
spring.jpa.open-in-view=false

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.foodtrack=INFO
logging.level.org.hibernate.SQL=WARN

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true