# ===============================
# ENTORNO LOCAL (DESARROLLO)
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/foodtrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Hikari (pool)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# JWT
jwt.secret=${JWT_SECRET:ChangeThisJwtSecretKeyBeforeProduction2026!}
jwt.expiration=${JWT_EXPIRATION:86400000}

# App
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}
app.bootstrap.admin-name=${APP_BOOTSTRAP_ADMIN_NAME:FoodTrack Admin}
app.bootstrap.admin-email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin@foodtrack.local}
app.bootstrap.admin-password=${APP_BOOTSTRAP_ADMIN_PASSWORD:Admin123!}